version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Running tests..."
      - curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh
      - databricks bundle deploy
