version: 2

sources:
  - name: tpch
    catalog: samples
    schema: tpch
    
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
